// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./codegen.sh

package api

// Provider registers all API endpoints with the schemaf framework.
// Wire up in go/main.go: app.AddApi(api.Provider)
func Provider() {
	Register(NewRoute[UpdateTodoReq, Todo](UpdateTodoEndpoint{}, "Updates the text and done status of a todo item.", ""))
	Register(NewRoute[GetTodoReq, GetTodoResp](GetTodoEndpoint{}, "Retrieves a single todo item by ID.", "Returns 404 if the todo does not exist."))
	Register(NewRoute[DeleteTodoReq, DeleteTodoResp](DeleteTodoEndpoint{}, "Deletes a todo item by ID.", ""))
	Register(NewRoute[ListTodosReq, ListTodosResp](ListTodosEndpoint{}, "Returns all todo items ordered by creation date.", "Returns an empty array if no todos exist."))
	Register(NewRoute[CreateTodoReq, Todo](CreateTodoEndpoint{}, "Creates a new todo item.", ""))
}
