#!/bin/bash
# schemaf.sh — runnable entrypoint for your project CLI. DO NOT EDIT.
#
# This script is a thin bootstrap wrapper. It delegates to `go run` so your
# compiled binary doesn't need to exist yet. The actual CLI — both framework
# commands (codegen, test, run, dev) and any custom subcommands you register
# via app.AddSubcommand() in main.go — lives entirely in Go.
#
# To add custom commands, use app.AddSubcommand() in your Go code.
# Do not add case branches here.
set -euo pipefail

if [ ! -f "$(dirname "$0")/schemaf.toml" ]; then
  echo "ERROR: schemaf.toml not found in the same directory as this script."
  echo "       Place schemaf.sh next to your schemaf.toml — see schemaf documentation."
  exit 1
fi

cd "$(dirname "$0")"

CMD="${1:-}"
shift 2>/dev/null || true

case "$CMD" in
  codegen)
    exec go run github.com/flocko-motion/schemaf/cmd/schemaf codegen all
    ;;
  test)
    go run github.com/flocko-motion/schemaf/cmd/schemaf codegen all

    # Start ephemeral test environment (no volumes — all data discarded after tests).
    PROJECT=$(grep '^name' schemaf.toml | cut -d= -f2)
    docker compose -f gen/compose.test.yml up -d --wait

    # Query the random host port Docker assigned to postgres:5432.
    PG_PORT=$(docker compose -f gen/compose.test.yml port postgres 5432 | awk -F: '{print $NF}')
    export DATABASE_URL="postgres://schemaf:dev@localhost:${PG_PORT}/${PROJECT}?sslmode=disable"

    # Set URL env vars for project sidecar services (generated by codegen).
    # shellcheck source=/dev/null
    source gen/test-env.sh

    # Run tests, capture exit code, then tear down regardless of result.
    go run github.com/flocko-motion/schemaf/cmd/schemaf test "$@"
    TEST_EXIT=$?
    docker compose -f gen/compose.test.yml down
    exit $TEST_EXIT
    ;;
  run)
    if [ ! -f gen/compose.gen.yml ]; then
      echo "gen/ not found — running codegen first..."
      go run github.com/flocko-motion/schemaf/cmd/schemaf codegen all
    fi
    exec docker compose -f gen/compose.gen.yml up "$@"
    ;;
  dev)
    if [ ! -f gen/compose.gen.yml ]; then
      echo "gen/ not found — running codegen first..."
      go run github.com/flocko-motion/schemaf/cmd/schemaf codegen all
    fi
    exec docker compose -f gen/compose.gen.yml -f gen/compose.dev.yml up "$@"
    ;;
  ""|--help|-h)
    echo "Usage: ./schemaf.sh <command> [args]"
    echo ""
    echo "  codegen    Generate all code (SQL, endpoints, TypeScript API client)"
    echo "  test       Regenerate code, then run all tests [--verbose] [--no-cache]"
    echo "  run        Start production compose setup"
    echo "  dev        Start development compose setup"
    exit 0
    ;;
  *)
    echo "Unknown command: $CMD" >&2
    echo "Run ./schemaf.sh --help for usage." >&2
    exit 1
    ;;
esac
