// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./codegen.sh

package main

import "github.com/flocko-motion/schemaf/schemaf"

func init() {
	schemaf.SetProjectName("schemaf-example")
}
