// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./schemaf.sh codegen

package main

import (
	"embed"
	"io/fs"
)

//go:embed all:frontend_dist
var frontendDist embed.FS

// FrontendFS returns the embedded frontend assets for production serving.
func FrontendFS() fs.FS {
	sub, _ := fs.Sub(frontendDist, "frontend_dist")
	return sub
}
