// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./codegen.sh
import * as m0 from "./api.test.ts"

const tests: Record<string, (url: string) => Promise<void>> = {
  ...m0,
}

const [,, funcName, baseUrl] = process.argv
const fn = tests[funcName]
if (!fn) {
  process.stderr.write(`unknown test: ${funcName}\n`)
  process.exit(1)
}
fn(baseUrl).catch((e: Error) => {
  process.stderr.write((e.stack ?? e.message) + "\n")
  process.exit(1)
})
