// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./codegen.sh
package tests

import (
	"net/http/httptest"
	"os/exec"
	"testing"

	schemafapi "schemaf.local/base/api"
	"schemaf.local/example/api"
)

func newTSTestServer(t *testing.T) *httptest.Server {
	t.Helper()
	schemafapi.Reset()
	api.Provider()
	srv := httptest.NewServer(schemafapi.NewMux())
	t.Cleanup(srv.Close)
	return srv
}

func runTSTest(t *testing.T, funcName string, srv *httptest.Server) {
	t.Helper()
	cmd := exec.Command("npx", "tsx", "runner.gen.ts", funcName, srv.URL)
	out, err := cmd.CombinedOutput()
	if len(out) > 0 {
		t.Log(string(out))
	}
	if err != nil {
		t.Fatalf("TS test %q failed", funcName)
	}
}

func TestHealth(t *testing.T) {
	srv := newTSTestServer(t)
	runTSTest(t, "testHealth", srv)
}

func TestClockTime(t *testing.T) {
	t.Skip("requires clock docker service")
}

