// Code generated by schemaf codegen. DO NOT EDIT.
// Regenerate with: ./codegen.sh

package db

import "embed"

// projectMigrations holds all SQL migration files embedded at build time.
//
//go:embed migrations/*.sql
var projectMigrations embed.FS

// Provider returns the embedded project migrations for registration with schemaf.
// Wire up in go/main.go: app.AddDb(db.Provider)
func Provider() embed.FS {
	return projectMigrations
}
