// Package apiclient provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.6.0 DO NOT EDIT.
package apiclient

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

// CreateTodoReq defines model for CreateTodoReq.
type CreateTodoReq struct {
	Text string `json:"text"`
}

// GetServerTimeResp defines model for GetServerTimeResp.
type GetServerTimeResp struct {
	Time time.Time `json:"time"`
}

// GetTodoResp defines model for GetTodoResp.
type GetTodoResp struct {
	Todo Todo `json:"todo"`
}

// ListTodosResp defines model for ListTodosResp.
type ListTodosResp struct {
	Todos []Todo `json:"todos"`
}

// Todo defines model for Todo.
type Todo struct {
	CreatedAt time.Time `json:"created_at"`
	Done      bool      `json:"done"`
	Id        string    `json:"id"`
	Text      string    `json:"text"`
}

// UpdateTodoReq defines model for UpdateTodoReq.
type UpdateTodoReq struct {
	Done bool   `json:"done"`
	Id   string `json:"id"`
	Text string `json:"text"`
}

// PostApiTodosJSONRequestBody defines body for PostApiTodos for application/json ContentType.
type PostApiTodosJSONRequestBody = CreateTodoReq

// PutApiTodosIdJSONRequestBody defines body for PutApiTodosId for application/json ContentType.
type PutApiTodosIdJSONRequestBody = UpdateTodoReq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PostApiEcho request
	PostApiEcho(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiTime request
	GetApiTime(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiTodos request
	GetApiTodos(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PostApiTodosWithBody request with any body
	PostApiTodosWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PostApiTodos(ctx context.Context, body PostApiTodosJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// DeleteApiTodosId request
	DeleteApiTodosId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetApiTodosId request
	GetApiTodosId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PutApiTodosIdWithBody request with any body
	PutApiTodosIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutApiTodosId(ctx context.Context, id string, body PutApiTodosIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PostApiEcho(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiEchoRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiTime(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiTimeRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiTodos(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiTodosRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTodosWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTodosRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PostApiTodos(ctx context.Context, body PostApiTodosJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPostApiTodosRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) DeleteApiTodosId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewDeleteApiTodosIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetApiTodosId(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetApiTodosIdRequest(c.Server, id)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiTodosIdWithBody(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiTodosIdRequestWithBody(c.Server, id, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutApiTodosId(ctx context.Context, id string, body PutApiTodosIdJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutApiTodosIdRequest(c.Server, id, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPostApiEchoRequest generates requests for PostApiEcho
func NewPostApiEchoRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/echo")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiTimeRequest generates requests for GetApiTime
func NewGetApiTimeRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/time")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiTodosRequest generates requests for GetApiTodos
func NewGetApiTodosRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/todos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPostApiTodosRequest calls the generic PostApiTodos builder with application/json body
func NewPostApiTodosRequest(server string, body PostApiTodosJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPostApiTodosRequestWithBody(server, "application/json", bodyReader)
}

// NewPostApiTodosRequestWithBody generates requests for PostApiTodos with any type of body
func NewPostApiTodosRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/todos")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

// NewDeleteApiTodosIdRequest generates requests for DeleteApiTodosId
func NewDeleteApiTodosIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/todos/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("DELETE", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetApiTodosIdRequest generates requests for GetApiTodosId
func NewGetApiTodosIdRequest(server string, id string) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/todos/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewPutApiTodosIdRequest calls the generic PutApiTodosId builder with application/json body
func NewPutApiTodosIdRequest(server string, id string, body PutApiTodosIdJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutApiTodosIdRequestWithBody(server, id, "application/json", bodyReader)
}

// NewPutApiTodosIdRequestWithBody generates requests for PutApiTodosId with any type of body
func NewPutApiTodosIdRequestWithBody(server string, id string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "id", id, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/todos/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PostApiEchoWithResponse request
	PostApiEchoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiEchoResponse, error)

	// GetApiTimeWithResponse request
	GetApiTimeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiTimeResponse, error)

	// GetApiTodosWithResponse request
	GetApiTodosWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiTodosResponse, error)

	// PostApiTodosWithBodyWithResponse request with any body
	PostApiTodosWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTodosResponse, error)

	PostApiTodosWithResponse(ctx context.Context, body PostApiTodosJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTodosResponse, error)

	// DeleteApiTodosIdWithResponse request
	DeleteApiTodosIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteApiTodosIdResponse, error)

	// GetApiTodosIdWithResponse request
	GetApiTodosIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiTodosIdResponse, error)

	// PutApiTodosIdWithBodyWithResponse request with any body
	PutApiTodosIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiTodosIdResponse, error)

	PutApiTodosIdWithResponse(ctx context.Context, id string, body PutApiTodosIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiTodosIdResponse, error)
}

type PostApiEchoResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r PostApiEchoResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiEchoResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiTimeResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetServerTimeResp
}

// Status returns HTTPResponse.Status
func (r GetApiTimeResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiTimeResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiTodosResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *ListTodosResp
}

// Status returns HTTPResponse.Status
func (r GetApiTodosResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiTodosResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PostApiTodosResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Todo
}

// Status returns HTTPResponse.Status
func (r PostApiTodosResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PostApiTodosResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type DeleteApiTodosIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
}

// Status returns HTTPResponse.Status
func (r DeleteApiTodosIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r DeleteApiTodosIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetApiTodosIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *GetTodoResp
}

// Status returns HTTPResponse.Status
func (r GetApiTodosIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetApiTodosIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PutApiTodosIdResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	JSON200      *Todo
}

// Status returns HTTPResponse.Status
func (r PutApiTodosIdResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutApiTodosIdResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PostApiEchoWithResponse request returning *PostApiEchoResponse
func (c *ClientWithResponses) PostApiEchoWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*PostApiEchoResponse, error) {
	rsp, err := c.PostApiEcho(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiEchoResponse(rsp)
}

// GetApiTimeWithResponse request returning *GetApiTimeResponse
func (c *ClientWithResponses) GetApiTimeWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiTimeResponse, error) {
	rsp, err := c.GetApiTime(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiTimeResponse(rsp)
}

// GetApiTodosWithResponse request returning *GetApiTodosResponse
func (c *ClientWithResponses) GetApiTodosWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetApiTodosResponse, error) {
	rsp, err := c.GetApiTodos(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiTodosResponse(rsp)
}

// PostApiTodosWithBodyWithResponse request with arbitrary body returning *PostApiTodosResponse
func (c *ClientWithResponses) PostApiTodosWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PostApiTodosResponse, error) {
	rsp, err := c.PostApiTodosWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTodosResponse(rsp)
}

func (c *ClientWithResponses) PostApiTodosWithResponse(ctx context.Context, body PostApiTodosJSONRequestBody, reqEditors ...RequestEditorFn) (*PostApiTodosResponse, error) {
	rsp, err := c.PostApiTodos(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePostApiTodosResponse(rsp)
}

// DeleteApiTodosIdWithResponse request returning *DeleteApiTodosIdResponse
func (c *ClientWithResponses) DeleteApiTodosIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*DeleteApiTodosIdResponse, error) {
	rsp, err := c.DeleteApiTodosId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseDeleteApiTodosIdResponse(rsp)
}

// GetApiTodosIdWithResponse request returning *GetApiTodosIdResponse
func (c *ClientWithResponses) GetApiTodosIdWithResponse(ctx context.Context, id string, reqEditors ...RequestEditorFn) (*GetApiTodosIdResponse, error) {
	rsp, err := c.GetApiTodosId(ctx, id, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetApiTodosIdResponse(rsp)
}

// PutApiTodosIdWithBodyWithResponse request with arbitrary body returning *PutApiTodosIdResponse
func (c *ClientWithResponses) PutApiTodosIdWithBodyWithResponse(ctx context.Context, id string, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutApiTodosIdResponse, error) {
	rsp, err := c.PutApiTodosIdWithBody(ctx, id, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiTodosIdResponse(rsp)
}

func (c *ClientWithResponses) PutApiTodosIdWithResponse(ctx context.Context, id string, body PutApiTodosIdJSONRequestBody, reqEditors ...RequestEditorFn) (*PutApiTodosIdResponse, error) {
	rsp, err := c.PutApiTodosId(ctx, id, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutApiTodosIdResponse(rsp)
}

// ParsePostApiEchoResponse parses an HTTP response from a PostApiEchoWithResponse call
func ParsePostApiEchoResponse(rsp *http.Response) (*PostApiEchoResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiEchoResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiTimeResponse parses an HTTP response from a GetApiTimeWithResponse call
func ParseGetApiTimeResponse(rsp *http.Response) (*GetApiTimeResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiTimeResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetServerTimeResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetApiTodosResponse parses an HTTP response from a GetApiTodosWithResponse call
func ParseGetApiTodosResponse(rsp *http.Response) (*GetApiTodosResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiTodosResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest ListTodosResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePostApiTodosResponse parses an HTTP response from a PostApiTodosWithResponse call
func ParsePostApiTodosResponse(rsp *http.Response) (*PostApiTodosResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PostApiTodosResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Todo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseDeleteApiTodosIdResponse parses an HTTP response from a DeleteApiTodosIdWithResponse call
func ParseDeleteApiTodosIdResponse(rsp *http.Response) (*DeleteApiTodosIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &DeleteApiTodosIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	return response, nil
}

// ParseGetApiTodosIdResponse parses an HTTP response from a GetApiTodosIdWithResponse call
func ParseGetApiTodosIdResponse(rsp *http.Response) (*GetApiTodosIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetApiTodosIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest GetTodoResp
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParsePutApiTodosIdResponse parses an HTTP response from a PutApiTodosIdWithResponse call
func ParsePutApiTodosIdResponse(rsp *http.Response) (*PutApiTodosIdResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutApiTodosIdResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest Todo
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
