// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: db/queries/todos.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const listTodos = `-- name: ListTodos :many
SELECT id, text, done, created_at FROM todos ORDER BY created_at DESC
`

type Todo struct {
	ID        string
	Text      string
	Done      bool
	CreatedAt time.Time
}

func (q *Queries) ListTodos(ctx context.Context) ([]Todo, error) {
	rows, err := q.db.QueryContext(ctx, listTodos)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(&i.ID, &i.Text, &i.Done, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTodo = `-- name: GetTodo :one
SELECT id, text, done, created_at FROM todos WHERE id = $1
`

func (q *Queries) GetTodo(ctx context.Context, id string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, getTodo, id)
	var i Todo
	err := row.Scan(&i.ID, &i.Text, &i.Done, &i.CreatedAt)
	return i, err
}

const createTodo = `-- name: CreateTodo :one
INSERT INTO todos (text) VALUES ($1) RETURNING id, text, done, created_at
`

func (q *Queries) CreateTodo(ctx context.Context, text string) (Todo, error) {
	row := q.db.QueryRowContext(ctx, createTodo, text)
	var i Todo
	err := row.Scan(&i.ID, &i.Text, &i.Done, &i.CreatedAt)
	return i, err
}

const updateTodo = `-- name: UpdateTodo :one
UPDATE todos SET text = $2, done = $3 WHERE id = $1 RETURNING id, text, done, created_at
`

type UpdateTodoParams struct {
	ID   string
	Text string
	Done bool
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	row := q.db.QueryRowContext(ctx, updateTodo, arg.ID, arg.Text, arg.Done)
	var i Todo
	err := row.Scan(&i.ID, &i.Text, &i.Done, &i.CreatedAt)
	return i, err
}

const deleteTodo = `-- name: DeleteTodo :exec
DELETE FROM todos WHERE id = $1
`

func (q *Queries) DeleteTodo(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTodo, id)
	return err
}

// DBTX is the interface for database operations.
type DBTX interface {
	ExecContext(context.Context, string, ...interface{}) (sql.Result, error)
	PrepareContext(context.Context, string) (*sql.Stmt, error)
	QueryContext(context.Context, string, ...interface{}) (*sql.Rows, error)
	QueryRowContext(context.Context, string, ...interface{}) *sql.Row
}

// New creates a new Queries instance.
func New(db DBTX) *Queries {
	return &Queries{db: db}
}

// Queries holds the database connection.
type Queries struct {
	db DBTX
}
